### ISSUE TITLE
[Renderer] --end release causes infinite output

### ISSUE THREAD

**Issue by markanini** [jcmoyer/Nuked-SC55#48]
`nuked-sc55-render --end release -o out.wav in.mid`
Starts an endless process making it necessary to kill the process.

I tested with the following midis:
[GRABBAG.zip](https://github.com/user-attachments/files/20852292/GRABBAG.zip)

[E1M1.zip](https://github.com/user-attachments/files/20853092/E1M1.zip)

If it helps, I can provide some general findings from opening one of the output files as a raw wave file in Cool Edit Pro, any normal audio player won't open the wave because the file can't be properly finalized when killing the process:

![Image](https://github.com/user-attachments/assets/4215176b-94fa-41bf-88b6-1785b6d66104)

Indeed, the file keep being written to despite lack of significant output. Some conditions for `--end release` to work as expected aren't optimized for my midi files at least. One quirk with Nuked SC-55 output that might be causing issues is the static 1.562% DC offset which makes the operative minimum amplitude -36.1 dB. Once DC offset is compensated for it's clear that underlying dynamic range is still close to the containing 96dB(16-bits), however.

Maybe one solution is to consider it a release condition for `--end release` when there is no output above -36.1dB(-30.1dB for f32) for more than four seconds. I don't know if this is helpful, I didn't really look at the current code as my knowledge in that area isn't extensive, so take my idea with a grain of salt.

Regarding DC offset in Nuked SC-55 output, I don't think it should be addressed given that it's a native behavior of the hardware. Although in practice it was probably removed by circuitry adjacent to the DAC portion of the synth-I haven't seen significant DC offset in waveforms of captured SC-55 audio.

**Comment by jcmoyer** [comment]
Just to double check, is this with the mk2 romset?

**Comment by markanini** [comment]
I'm having the issue with mk1 1.21 ROM.
I tested with mk2 ROM and can't recreate the issue. Interestingly the DC offset is fixed too with mk2 ROM.

**Comment by akse0435** [comment]
Hi,

I'm experiencing this exact same issue when rendering some MIDI files with the mk1 1.21 romset and --end release. It just renders infinite silence after the midi file has ended. It never happens with the mk2 romset, or with --end set to cut. I've build the emulator on Windows 10 a few days ago from the latest commit.
What could be happening?
Thank you in advance.

**Comment by jcmoyer** [comment]
Thanks, I can reproduce the issue.

**Comment by akse0435** [comment]
Sounds good, thank you.

**Comment by mckuhei** [comment]
I believe the problem is not yet resolved. If multiple instances are enabled, the DC offset will accumulate, eventually causing the problem to reappear.

**Comment by mckuhei** [comment]
The best solution is to add a 10-second timer to forcibly cut off recording after the MIDI playback ends.

**Comment by jcmoyer** [comment]
Silence is processed per instance, so rendering with more instances shouldn't keep the renderer running. Can you share a test case reproducing the problem?

**Comment by mckuhei** [comment]
Oh thats make sense
